CONFIG_USB_DEVICE_STACK_NEXT=y
# CONFIG_USBD_CDC_ACM_CLASS=y
# CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_USBD_MIDI2_CLASS=y
CONFIG_I2C=y
CONFIG_MULTITHREADING=y

# Thread monitoring settings
CONFIG_THREAD_NAME=y
# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_AUTO=y
# CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=5
