#ifndef CONFIG_H
#define CONFIG_H

#define ADC_READ_TASK_STACK_SIZE 2048
#define ADC_READ_TASK_PRIORITY 1
#define ADC_PARSE_TASK_STACK_SIZE 2048
#define ADC_PARSE_TASK_PRIORITY 2
#define ADC_CHANNELS_USED 0, 1
#define ADC_CHANNELS_LENGTH 2
#define ADC_DEADBAND 1

#endif // CONFIG_H
