#ifndef CONFIG_H
#define CONFIG_H

#define ADC_READ_TASK_STACK_SIZE 1024
#define ADC_READ_TASK_PRIORITY 1
#define ADC_PARSE_TASK_STACK_SIZE 1024
#define ADC_PARSE_TASK_PRIORITY 2
#define ADC_CHANNELS_USED 0, 1
#define ADC_CHANNELS_LENGTH 2
#define ADC_DEADBAND 1

#define MIDI_SEND_TASK_STACK_SIZE 1024
#define MIDI_SEND_TASK_PRIORITY 3
#define MIDI_CONTROLLER 7

#endif // CONFIG_H
