#ifndef CONFIG_H
#define CONFIG_H

#define ADC_READ_TASK_STACK_SIZE 1024
#define ADC_READ_TASK_PRIORITY 3
#define ADC_PARSE_TASK_STACK_SIZE 1024
#define ADC_PARSE_TASK_PRIORITY 2
#define ADC_CHANNELS_USED 2, 3
#define ADC_DEADBAND 1

#define MIDI_SEND_TASK_STACK_SIZE 1024
#define MIDI_SEND_TASK_PRIORITY 1
#define MIDI_CONTROLLER 7

#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))

#endif // CONFIG_H
